linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - godox
    - goerr113
    - gofumpt
    - gomnd
    - nestif
    - nlreturn
    - paralleltest
    - wrapcheck
    - wsl

linters-settings:
  lll:
    line-length: 140
    tab-width: 4